arm_ffa: Add missing ffa_notifier_ops structure definition
The ffa_notifier_ops structure was referenced in struct ffa_ops but
not defined, causing compilation failures in drivers/tee/optee/ffa_abi.c
with errors:

  drivers/tee/optee/ffa_abi.c:821:43: error: invalid use of undefined
    type 'const struct ffa_notifier_ops'
  drivers/tee/optee/ffa_abi.c:839:48: error: invalid use of undefined
    type 'const struct ffa_notifier_ops'
  drivers/tee/optee/ffa_abi.c:863:43: error: invalid use of undefined
    type 'const struct ffa_notifier_ops'
  drivers/tee/optee/ffa_abi.c:982:26: error: invalid use of undefined
    type 'const struct ffa_notifier_ops'

Add the complete ffa_notifier_ops structure definition with all required
function pointers for notification handling:
- sched_recv_cb_register/unregister for scheduling callbacks
- notify_request/relinquish for notification management
- notify_send for sending notifications

Also add the required callback function typedefs (ffa_sched_recv_cb and
ffa_notifier_cb) that are used by the notifier operations.

This change is backported from upstream Linux kernel to fix the
compilation issue while maintaining compatibility with the existing
OP-TEE FFA ABI implementation.

Change-Id: Iaaa6d3016c6e46e876befd1b3dc859adcd95400e
Signed-off-by: Ananya Ghosh <ananghos@qti.qualcomm.com>