xhci-trace: fix to resolve the warning in debug build
drivers/usb/host/./xhci-trace.h: In function
'trace_event_get_offsets_xhci_log_msg':
./include/trace/trace_events.h:256:27: error: function
'trace_event_get_offsets_xhci_log_msg' can never be inlined
because it uses variable argument lists
  256 | static inline notrace int trace_event_get_offsets_##call( \
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/host/./xhci-trace.h:28:1: note: in expansion of macro
'DECLARE_EVENT_CLASS'
   28 | DECLARE_EVENT_CLASS(xhci_log_msg,
      | ^~~~~~~~~~~~~~~~~~~

samples/trace_events/./trace-events-sample.h: In function
'trace_event_get_offsets_foo_bar':
./include/trace/trace_events.h:256:27: error: function
'trace_event_get_offsets_foo_bar' can never be inlined
because it uses variable argument lists
  256 | static inline notrace int trace_event_get_offsets_##call( \
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~
./include/trace/trace_events.h:40:9: note: in expansion of macro
'DECLARE_EVENT_CLASS'
   40 |         DECLARE_EVENT_CLASS(name, \
      |         ^~~~~~~~~~~~~~~~~~~
samples/trace_events/./trace-events-sample.h:277:1: note:
in expansion of macro 'TRACE_EVENT'
  277 | TRACE_EVENT(foo_bar,
      | ^~~~~~~~~~~

Change-Id: I11ec974323209d56cd17ebf5dd69b7c22c087dae
Signed-off-by: Timple Raj M <quic_timple@quicinc.com>